/**
 * FractalPulse: Edge AI Health Monitoring
 * Main firmware for ESP32 microcontroller
 * 
 * Runs TFLite Micro model for on-device inference
 * Communicates with host via UART/TCP
 */

#include <stdio.h>
#include <stdint.h>
#include <math.h>
#include <string.h>

#include "esp_system.h"
#include "esp_event.h"
#include "nvs_flash.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

// Placeholder: will be auto-generated by training pipeline
#include "model_data.c"

// ============================================================================
// Configuration
// ============================================================================

#define FEATURE_WINDOW_SIZE 2500  // 10 seconds @ 250 Hz
#define ECG_SAMPLING_RATE   250
#define ADC_PIN             GPIO_NUM_32
#define UART_TX_PIN         GPIO_NUM_17
#define UART_RX_PIN         GPIO_NUM_16

// TFLite model constants
#define ARENA_SIZE 10 * 1024  // 10 KB for model + activations
uint8_t g_arena[ARENA_SIZE];

// ============================================================================
// Feature Extraction (Same as Python, implemented in C)
// ============================================================================

/**
 * Simple R-peak detection using threshold-based peak finding
 */
int detect_r_peaks(float* ecg_signal, int signal_len, int* peak_indices) {
    int num_peaks = 0;
    float threshold = 0.5f;
    
    for (int i = 1; i < signal_len - 1; i++) {
        if (ecg_signal[i] > threshold && 
            ecg_signal[i] > ecg_signal[i-1] && 
            ecg_signal[i] >= ecg_signal[i+1]) {
            peak_indices[num_peaks++] = i;
        }
    }
    return num_peaks;
}

/**
 * Extract ECG features: HR, HRV metrics
 */
typedef struct {
    float hr;
    float hrv_sdnn;
    float hrv_pnn50;
    float hrv_rmssd;
    float mean_rr;
    float arrhythmia_risk;
} ECGFeatures;

ECGFeatures extract_ecg_features(float* ecg_signal, int signal_len) {
    ECGFeatures feat = {0};
    
    int peak_indices[256];
    int num_peaks = detect_r_peaks(ecg_signal, signal_len, peak_indices);
    
    if (num_peaks < 2) {
        return feat;
    }
    
    // Compute RR intervals
    float rr_intervals[256];
    for (int i = 0; i < num_peaks - 1; i++) {
        rr_intervals[i] = (float)(peak_indices[i+1] - peak_indices[i]) / ECG_SAMPLING_RATE;
    }
    
    // Heart rate (mean)
    float mean_rr = 0.0f;
    for (int i = 0; i < num_peaks - 1; i++) {
        mean_rr += rr_intervals[i];
    }
    mean_rr /= (num_peaks - 1);
    feat.hr = 60.0f / mean_rr;
    feat.mean_rr = mean_rr * 1000;  // Convert to ms
    
    // SDNN (std dev of RR intervals in ms)
    float variance = 0.0f;
    for (int i = 0; i < num_peaks - 1; i++) {
        float diff = rr_intervals[i] * 1000 - feat.mean_rr;
        variance += diff * diff;
    }
    feat.hrv_sdnn = sqrtf(variance / (num_peaks - 1));
    
    // pNN50 and RMSSD
    int nn50 = 0;
    float rmssd_sum = 0.0f;
    for (int i = 0; i < num_peaks - 2; i++) {
        float diff_ms = fabsf(rr_intervals[i] * 1000 - rr_intervals[i+1] * 1000);
        if (diff_ms > 50.0f) nn50++;
        rmssd_sum += diff_ms * diff_ms;
    }
    feat.hrv_pnn50 = 100.0f * nn50 / (num_peaks - 2);
    feat.hrv_rmssd = sqrtf(rmssd_sum / (num_peaks - 2));
    
    // Simple arrhythmia detection
    feat.arrhythmia_risk = (feat.hr < 40 || feat.hr > 100) ? 1.0f : 0.0f;
    
    return feat;
}

// ============================================================================
// TFLite Inference
// ============================================================================

/**
 * Run inference on extracted features using quantized TFLite model
 */
typedef struct {
    uint8_t class_idx;
    float confidence;
    float scores[2];
} InferenceResult;

InferenceResult run_inference(ECGFeatures* features) {
    InferenceResult result = {0};
    
    static tflite::MicroInterpreter* interpreter = NULL;
    
    if (interpreter == NULL) {
        // Initialize TFLite model (one-time setup)
        const tflite::Model* model = tflite::GetModel(g_fractal_pulse_model_data);
        
        static tflite::MicroMutableOpResolver<4> micro_op_resolver;
        micro_op_resolver.AddFullyConnected();
        micro_op_resolver.AddRelu();
        micro_op_resolver.AddSoftmax();
        
        static tflite::MicroInterpreter static_interpreter(
            model, micro_op_resolver, g_arena, ARENA_SIZE);
        interpreter = &static_interpreter;
        
        interpreter->AllocateTensors();
    }
    
    // Prepare input tensor
    TfLiteTensor* input = interpreter->input(0);
    float input_features[] = {
        features->hr,
        features->hrv_sdnn,
        features->hrv_pnn50,
        features->hrv_rmssd,
        features->mean_rr,
        features->arrhythmia_risk,
    };
    
    memcpy(input->data.f, input_features, sizeof(input_features));
    
    // Run inference
    TfLiteStatus invoke_status = interpreter->Invoke();
    if (invoke_status != kTfLiteOk) {
        printf("ERROR: Inference failed\n");
        result.class_idx = 0;
        result.confidence = 0.5f;
        return result;
    }
    
    // Get output
    TfLiteTensor* output = interpreter->output(0);
    result.scores[0] = output->data.f[0];
    result.scores[1] = output->data.f[1];
    result.class_idx = (output->data.f[1] > output->data.f[0]) ? 1 : 0;
    result.confidence = (result.class_idx == 0) ? result.scores[0] : result.scores[1];
    
    return result;
}

// ============================================================================
// Alert Logic
// ============================================================================

void trigger_alert(InferenceResult* result) {
    if (result->class_idx == 1 && result->confidence > 0.6f) {
        // Simulated alert: print to UART + would control vibration motor
        printf("ALERT: Anomaly detected! Confidence: %.1f%%\n", result->confidence * 100);
        // TODO: Set GPIO for vibration/buzzer
    }
}

// ============================================================================
// Main Application Loop
// ============================================================================

static float ecg_buffer[FEATURE_WINDOW_SIZE];
static int ecg_buffer_pos = 0;

void app_main(void) {
    printf("FractalPulse v1.0 - Starting...\n");
    
    // Initialize NVS (non-volatile storage)
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }
    
    printf("Model loaded: %zu bytes\n", g_fractal_pulse_model_data_len);
    
    // Main monitoring loop
    while (1) {
        // TODO: Read ADC from ECG sensor
        // For now, simulate with synthetic data
        ecg_buffer[ecg_buffer_pos++] = sinf(2 * 3.14159f * ecg_buffer_pos / 250.0f);
        
        // When buffer is full, run feature extraction + inference
        if (ecg_buffer_pos >= FEATURE_WINDOW_SIZE) {
            printf("Running inference on %d samples...\n", ecg_buffer_pos);
            
            ECGFeatures features = extract_ecg_features(ecg_buffer, FEATURE_WINDOW_SIZE);
            InferenceResult result = run_inference(&features);
            
            printf("HR: %.1f bpm, HRV_SDNN: %.1f ms\n", features.hr, features.hrv_sdnn);
            printf("Inference: %s (confidence: %.1f%%)\n", 
                   result.class_idx == 0 ? "Normal" : "Anomaly", 
                   result.confidence * 100);
            
            trigger_alert(&result);
            
            // Reset buffer
            ecg_buffer_pos = 0;
        }
        
        vTaskDelay(1);  // 1ms task delay
    }
}
